spring:
  application:
    name: backend
  datasource:

  # toss:
  #   secret-key: ${TOSS_SECRET_KEY}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
